name = "lastfm-mcp"
main = "src/index.ts"
compatibility_date = "2026-04-08"

[vars]
LASTFM_API_BASE_URL = "https://ws.audioscrobbler.com/2.0/"
LASTFM_USER_AGENT = "lastfm-mcp-worker/0.1.0"

[secrets]
required = [ "LASTFM_API_KEY" ]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
